name: aptabase_flutter_plus_example
description: Flutter example for aptabase_flutter_plus.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

resolution: workspace

dependencies:
  aptabase_flutter_plus:
    path: ..
  aptabase_storage_shared_preferences_plus:
    path: ../../aptabase_storage_shared_preferences_plus
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
