name: aptabase_plus_workspace
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - packages/aptabase_plus
  - packages/aptabase_plus/example
  - packages/aptabase_flutter_plus
  - packages/aptabase_flutter_plus/example
  - packages/aptabase_storage_shared_preferences_plus
  - packages/aptabase_storage_shared_preferences_plus/example
  - packages/aptabase_storage_hive_ce_plus
  - packages/aptabase_storage_hive_ce_plus/example
