name: aptabase_plus_workspace
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - packages/aptabase_plus
  - packages/aptabase_plus_flutter
  - packages/aptabase_plus_hive_ce
  - example
