name: aptabase_plus_workspace
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - packages/aptabase_plus
  - packages/aptabase_plus_flutter
  - packages/aptabase_plus_hive_ce
  - example

dev_dependencies:
  lints: ^6.1.0
  melos: ^7.8.2
